
#Lists of animations from here: http://doc.aldebaran.com/2-8/naoqi/motion/alanimationplayer-advanced.html#animationplayer-tags-nao
Pepper_animations = {
## new animations since NAOqi 2.8
"Center_Neutral_AFF_01" : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Neutral_AFF_01",
"Center_Neutral_AFF_02" : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Neutral_AFF_02",
"Center_Neutral_AFF_04" : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Neutral_AFF_04",
"Center_Neutral_AFF_05" : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Neutral_AFF_05",
"Center_Neutral_AFF_06" : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Neutral_AFF_06",
"Center_Neutral_AFF_07" : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Neutral_AFF_07",
"Center_Neutral_AFF_08" : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Neutral_AFF_08",
"Center_Neutral_AFF_09" : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Neutral_AFF_09",
"Center_Neutral_AFF_10" : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Neutral_AFF_10",
"Center_Neutral_AFF_11" : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Neutral_AFF_11",
"Center_Neutral_AFF_12" : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Neutral_AFF_12",
"Center_Neutral_AFF_13" : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Neutral_AFF_13",
"Center_Slow_AFF_01"    : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Slow_AFF_01",
"Center_Slow_AFF_02"    : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Slow_AFF_02",
"Center_Slow_AFF_03"    : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Slow_AFF_03",
"Center_Slow_AFF_05"    : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Slow_AFF_05",
"Center_Slow_AFF_06"    : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Slow_AFF_06",
"Center_Strong_AFF_01"  : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Strong_AFF_01",
"Center_Strong_AFF_02"  : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Strong_AFF_02",
"Center_Strong_AFF_04"  : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Strong_AFF_04",
"Center_Strong_AFF_05"  : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Strong_AFF_05",
"Center_Strong_AFF_06"  : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Strong_AFF_06",
"Center_Strong_AFF_07"  : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Strong_AFF_07",
"Center_Strong_AFF_08"  : "animations/Stand/BodyTalk/BodyLanguage/NAO/Center_Strong_AFF_08",
"Left_Neutral_AFF_02"   : "animations/Stand/BodyTalk/BodyLanguage/NAO/Left_Neutral_AFF_02",
"Left_Neutral_AFF_04"   : "animations/Stand/BodyTalk/BodyLanguage/NAO/Left_Neutral_AFF_04",
"Left_Neutral_AFF_05"   : "animations/Stand/BodyTalk/BodyLanguage/NAO/Left_Neutral_AFF_05",
"Left_Neutral_AFF_06"   : "animations/Stand/BodyTalk/BodyLanguage/NAO/Left_Neutral_AFF_06",
"Left_Slow_AFF_01"      : "animations/Stand/BodyTalk/BodyLanguage/NAO/Left_Slow_AFF_01",
"Left_Slow_AFF_02"      : "animations/Stand/BodyTalk/BodyLanguage/NAO/Left_Slow_AFF_02",
"Left_Slow_AFF_03"      : "animations/Stand/BodyTalk/BodyLanguage/NAO/Left_Slow_AFF_03",
"Left_Strong_AFF_02"    : "animations/Stand/BodyTalk/BodyLanguage/NAO/Left_Strong_AFF_02",
"Right_Neutral_AFF_02"  : "animations/Stand/BodyTalk/BodyLanguage/NAO/Right_Neutral_AFF_02",
"Right_Neutral_AFF_04"  : "animations/Stand/BodyTalk/BodyLanguage/NAO/Right_Neutral_AFF_04",
"Right_Neutral_AFF_05"  : "animations/Stand/BodyTalk/BodyLanguage/NAO/Right_Neutral_AFF_05",
"Right_Neutral_AFF_06"  : "animations/Stand/BodyTalk/BodyLanguage/NAO/Right_Neutral_AFF_06",
"Right_Slow_AFF_01"     : "animations/Stand/BodyTalk/BodyLanguage/NAO/Right_Slow_AFF_01",
"Right_Slow_AFF_02"     : "animations/Stand/BodyTalk/BodyLanguage/NAO/Right_Slow_AFF_02",
"Right_Slow_AFF_03"     : "animations/Stand/BodyTalk/BodyLanguage/NAO/Right_Slow_AFF_03",
"Right_Strong_AFF_02"   : "animations/Stand/BodyTalk/BodyLanguage/NAO/Right_Strong_AFF_02",
"Center_Neutral_ENU_01" : "animations/Stand/Enumeration/NAO/Center_Neutral_ENU_01",
"Center_Neutral_ENU_02" : "animations/Stand/Enumeration/NAO/Center_Neutral_ENU_02",
"Center_Neutral_ENU_03" : "animations/Stand/Enumeration/NAO/Center_Neutral_ENU_03",
"Center_Neutral_ENU_04" : "animations/Stand/Enumeration/NAO/Center_Neutral_ENU_04",
"Center_Neutral_ENU_06" : "animations/Stand/Enumeration/NAO/Center_Neutral_ENU_06",
"Center_Neutral_ENU_07" : "animations/Stand/Enumeration/NAO/Center_Neutral_ENU_07",
"Center_Slow_ENU_01"    : "animations/Stand/Enumeration/NAO/Center_Slow_ENU_01",
"Center_Slow_ENU_02"    : "animations/Stand/Enumeration/NAO/Center_Slow_ENU_02",
"Center_Slow_ENU_03"    : "animations/Stand/Enumeration/NAO/Center_Slow_ENU_03",
"Center_Slow_ENU_04"    : "animations/Stand/Enumeration/NAO/Center_Slow_ENU_04",
"Center_Strong_ENU_01"  : "animations/Stand/Enumeration/NAO/Center_Strong_ENU_01",
"Center_Strong_ENU_02"  : "animations/Stand/Enumeration/NAO/Center_Strong_ENU_02",
"Center_Strong_ENU_03"  : "animations/Stand/Enumeration/NAO/Center_Strong_ENU_03",
"Left_Neutral_ENU_01"   : "animations/Stand/Enumeration/NAO/Left_Neutral_ENU_01",
"Left_Neutral_ENU_02"   : "animations/Stand/Enumeration/NAO/Left_Neutral_ENU_02",
"Left_Neutral_ENU_03"   : "animations/Stand/Enumeration/NAO/Left_Neutral_ENU_03",
"Left_Neutral_ENU_04"   : "animations/Stand/Enumeration/NAO/Left_Neutral_ENU_04",
"Left_Neutral_ENU_05"   : "animations/Stand/Enumeration/NAO/Left_Neutral_ENU_05",
"Left_Strong_ENU_02"    : "animations/Stand/Enumeration/NAO/Left_Strong_ENU_02",
"Left_Strong_ENU_03"    : "animations/Stand/Enumeration/NAO/Left_Strong_ENU_03",
"Left_Strong_ENU_04"    : "animations/Stand/Enumeration/NAO/Left_Strong_ENU_04",
"Right_Neutral_ENU_01"  : "animations/Stand/Enumeration/NAO/Right_Neutral_ENU_01",
"Right_Neutral_ENU_02"  : "animations/Stand/Enumeration/NAO/Right_Neutral_ENU_02",
"Right_Neutral_ENU_03"  : "animations/Stand/Enumeration/NAO/Right_Neutral_ENU_03",
"Right_Neutral_ENU_04"  : "animations/Stand/Enumeration/NAO/Right_Neutral_ENU_04",
"Right_Neutral_ENU_05"  : "animations/Stand/Enumeration/NAO/Right_Neutral_ENU_05",
"Right_Strong_ENU_02"   : "animations/Stand/Enumeration/NAO/Right_Strong_ENU_02",
"Right_Strong_ENU_03"   : "animations/Stand/Enumeration/NAO/Right_Strong_ENU_03",
"Right_Strong_ENU_04"   : "animations/Stand/Enumeration/NAO/Right_Strong_ENU_04",
"Center_Neutral_EXC_01" : "animations/Stand/Exclamation/NAO/Center_Neutral_EXC_01",
"Center_Neutral_EXC_02" : "animations/Stand/Exclamation/NAO/Center_Neutral_EXC_02",
"Center_Neutral_EXC_03" : "animations/Stand/Exclamation/NAO/Center_Neutral_EXC_03",
"Center_Neutral_EXC_04" : "animations/Stand/Exclamation/NAO/Center_Neutral_EXC_04",
"Center_Neutral_EXC_05" : "animations/Stand/Exclamation/NAO/Center_Neutral_EXC_05",
"Center_Neutral_EXC_06" : "animations/Stand/Exclamation/NAO/Center_Neutral_EXC_06",
"Center_Neutral_EXC_07" : "animations/Stand/Exclamation/NAO/Center_Neutral_EXC_07",
"Center_Neutral_EXC_08" : "animations/Stand/Exclamation/NAO/Center_Neutral_EXC_08",
"Center_Slow_EXC_01"    : "animations/Stand/Exclamation/NAO/Center_Slow_EXC_01",
"Center_Slow_EXC_02"    : "animations/Stand/Exclamation/NAO/Center_Slow_EXC_02",
"Center_Slow_EXC_03"    : "animations/Stand/Exclamation/NAO/Center_Slow_EXC_03",
"Center_Strong_EXC_03"  : "animations/Stand/Exclamation/NAO/Center_Strong_EXC_03",
"Center_Strong_EXC_04"  : "animations/Stand/Exclamation/NAO/Center_Strong_EXC_04",
"Center_Strong_EXC_05"  : "animations/Stand/Exclamation/NAO/Center_Strong_EXC_05",
"Center_Strong_EXC_06"  : "animations/Stand/Exclamation/NAO/Center_Strong_EXC_06",
"Center_Strong_EXC_08"  : "animations/Stand/Exclamation/NAO/Center_Strong_EXC_08",
"Center_Strong_EXC_09"  : "animations/Stand/Exclamation/NAO/Center_Strong_EXC_09",
"Center_Strong_EXC_10"  : "animations/Stand/Exclamation/NAO/Center_Strong_EXC_10",
"Left_Neutral_EXC_02"   : "animations/Stand/Exclamation/NAO/Left_Neutral_EXC_02",
"Left_Neutral_EXC_05"   : "animations/Stand/Exclamation/NAO/Left_Neutral_EXC_05",
"Left_Strong_EXC_01"    : "animations/Stand/Exclamation/NAO/Left_Strong_EXC_01",
"Left_Strong_EXC_02"    : "animations/Stand/Exclamation/NAO/Left_Strong_EXC_02",
"Left_Strong_EXC_03"    : "animations/Stand/Exclamation/NAO/Left_Strong_EXC_03",
"Left_Strong_EXC_04"    : "animations/Stand/Exclamation/NAO/Left_Strong_EXC_04",
"Right_Neutral_EXC_02"  : "animations/Stand/Exclamation/NAO/Right_Neutral_EXC_02",
"Right_Neutral_EXC_05"  : "animations/Stand/Exclamation/NAO/Right_Neutral_EXC_05",
"Right_Strong_EXC_01"   : "animations/Stand/Exclamation/NAO/Right_Strong_EXC_01",
"Right_Strong_EXC_02"   : "animations/Stand/Exclamation/NAO/Right_Strong_EXC_02",
"Right_Strong_EXC_03"   : "animations/Stand/Exclamation/NAO/Right_Strong_EXC_03",
"Right_Strong_EXC_04"   : "animations/Stand/Exclamation/NAO/Right_Strong_EXC_04",
"Center_Neutral_NEG_01" : "animations/Stand/Negation/NAO/Center_Neutral_NEG_01",
"Center_Neutral_NEG_02" : "animations/Stand/Negation/NAO/Center_Neutral_NEG_02",
"Center_Neutral_NEG_03" : "animations/Stand/Negation/NAO/Center_Neutral_NEG_03",
"Center_Neutral_NEG_04" : "animations/Stand/Negation/NAO/Center_Neutral_NEG_04",
"Center_Slow_NEG_01"    : "animations/Stand/Negation/NAO/Center_Slow_NEG_01",
"Center_Slow_NEG_02"    : "animations/Stand/Negation/NAO/Center_Slow_NEG_02",
"Center_Strong_NEG_01"  : "animations/Stand/Negation/NAO/Center_Strong_NEG_01",
"Center_Strong_NEG_03"  : "animations/Stand/Negation/NAO/Center_Strong_NEG_03",
"Center_Strong_NEG_04"  : "animations/Stand/Negation/NAO/Center_Strong_NEG_04",
"Center_Strong_NEG_05"  : "animations/Stand/Negation/NAO/Center_Strong_NEG_05",
"Left_Neutral_NEG_01"   : "animations/Stand/Negation/NAO/Left_Neutral_NEG_01",
"Left_Strong_NEG_01"    : "animations/Stand/Negation/NAO/Left_Strong_NEG_01",
"Left_Strong_NEG_02"    : "animations/Stand/Negation/NAO/Left_Strong_NEG_02",
"Left_Strong_NEG_03"    : "animations/Stand/Negation/NAO/Left_Strong_NEG_03",
"Left_Strong_NEG_04"    : "animations/Stand/Negation/NAO/Left_Strong_NEG_04",
"Right_Neutral_NEG_01"  : "animations/Stand/Negation/NAO/Right_Neutral_NEG_01",
"Right_Strong_NEG_01"   : "animations/Stand/Negation/NAO/Right_Strong_NEG_01",
"Right_Strong_NEG_02"   : "animations/Stand/Negation/NAO/Right_Strong_NEG_02",
"Right_Strong_NEG_03"   : "animations/Stand/Negation/NAO/Right_Strong_NEG_03",
"Right_Strong_NEG_04"   : "animations/Stand/Negation/NAO/Right_Strong_NEG_04",
"Center_Neutral_QUE_01" : "animations/Stand/Question/NAO/Center_Neutral_QUE_01",
"Center_Neutral_QUE_02" : "animations/Stand/Question/NAO/Center_Neutral_QUE_02",
"Center_Neutral_QUE_03" : "animations/Stand/Question/NAO/Center_Neutral_QUE_03",
"Center_Neutral_QUE_04" : "animations/Stand/Question/NAO/Center_Neutral_QUE_04",
"Center_Neutral_QUE_05" : "animations/Stand/Question/NAO/Center_Neutral_QUE_05",
"Center_Neutral_QUE_06" : "animations/Stand/Question/NAO/Center_Neutral_QUE_06",
"Center_Neutral_QUE_08" : "animations/Stand/Question/NAO/Center_Neutral_QUE_08",
"Center_Neutral_QUE_09" : "animations/Stand/Question/NAO/Center_Neutral_QUE_09",
"Center_Neutral_QUE_10" : "animations/Stand/Question/NAO/Center_Neutral_QUE_10",
"Center_Slow_QUE_01"    : "animations/Stand/Question/NAO/Center_Slow_QUE_01",
"Center_Slow_QUE_02"    : "animations/Stand/Question/NAO/Center_Slow_QUE_02",
"Center_Slow_QUE_03"    : "animations/Stand/Question/NAO/Center_Slow_QUE_03",
"Center_Strong_QUE_01"  : "animations/Stand/Question/NAO/Center_Strong_QUE_01",
"Center_Strong_QUE_02"  : "animations/Stand/Question/NAO/Center_Strong_QUE_02",
"Center_Strong_QUE_03"  : "animations/Stand/Question/NAO/Center_Strong_QUE_03",
"Left_Neutral_QUE_01"   : "animations/Stand/Question/NAO/Left_Neutral_QUE_01",
"Left_Neutral_QUE_02"   : "animations/Stand/Question/NAO/Left_Neutral_QUE_02",
"Left_Neutral_QUE_03"   : "animations/Stand/Question/NAO/Left_Neutral_QUE_03",
"Right_Neutral_QUE_01"  : "animations/Stand/Question/NAO/Right_Neutral_QUE_01",
"Right_Neutral_QUE_02"  : "animations/Stand/Question/NAO/Right_Neutral_QUE_02",
"Right_Neutral_QUE_03"  : "animations/Stand/Question/NAO/Right_Neutral_QUE_03",
"Center_Neutral_SAO_01" : "animations/Stand/Self & others/NAO/Center_Neutral_SAO_01",
"Center_Neutral_SAO_02" : "animations/Stand/Self & others/NAO/Center_Neutral_SAO_02",
"Center_Neutral_SAO_03" : "animations/Stand/Self & others/NAO/Center_Neutral_SAO_03",
"Center_Neutral_SAO_04" : "animations/Stand/Self & others/NAO/Center_Neutral_SAO_04",
"Center_Neutral_SAO_05" : "animations/Stand/Self & others/NAO/Center_Neutral_SAO_05",
"Center_Strong_SAO_01"  : "animations/Stand/Self & others/NAO/Center_Strong_SAO_01",
"Center_Strong_SAO_02"  : "animations/Stand/Self & others/NAO/Center_Strong_SAO_02",
"Left_Neutral_SAO_01"   : "animations/Stand/Self & others/NAO/Left_Neutral_SAO_01",
"Left_Neutral_SAO_02"   : "animations/Stand/Self & others/NAO/Left_Neutral_SAO_02",
"Left_Neutral_SAO_03"   : "animations/Stand/Self & others/NAO/Left_Neutral_SAO_03",
"Left_Neutral_SAO_04"   : "animations/Stand/Self & others/NAO/Left_Neutral_SAO_04",
"Left_Neutral_SAO_05"   : "animations/Stand/Self & others/NAO/Left_Neutral_SAO_05",
"Left_Neutral_SAO_06"   : "animations/Stand/Self & others/NAO/Left_Neutral_SAO_06",
"Left_Slow_SAO_01"      : "animations/Stand/Self & others/NAO/Left_Slow_SAO_01",
"Left_Slow_SAO_02"      : "animations/Stand/Self & others/NAO/Left_Slow_SAO_02",
"Left_Strong_SAO_01"    : "animations/Stand/Self & others/NAO/Left_Strong_SAO_01",
"Left_Strong_SAO_02"    : "animations/Stand/Self & others/NAO/Left_Strong_SAO_02",
"Left_Strong_SAO_03"    : "animations/Stand/Self & others/NAO/Left_Strong_SAO_03",
"Left_Strong_SAO_04"    : "animations/Stand/Self & others/NAO/Left_Strong_SAO_04",
"Left_Strong_SAO_05"    : "animations/Stand/Self & others/NAO/Left_Strong_SAO_05",
"Right_Neutral_SAO_01"  : "animations/Stand/Self & others/NAO/Right_Neutral_SAO_01",
"Right_Neutral_SAO_02"  : "animations/Stand/Self & others/NAO/Right_Neutral_SAO_02",
"Right_Neutral_SAO_03"  : "animations/Stand/Self & others/NAO/Right_Neutral_SAO_03",
"Right_Neutral_SAO_04"  : "animations/Stand/Self & others/NAO/Right_Neutral_SAO_04",
"Right_Neutral_SAO_05"  : "animations/Stand/Self & others/NAO/Right_Neutral_SAO_05",
"Right_Neutral_SAO_06"  : "animations/Stand/Self & others/NAO/Right_Neutral_SAO_06",
"Right_Slow_SAO_01"     : "animations/Stand/Self & others/NAO/Right_Slow_SAO_01",
"Right_Slow_SAO_02"     : "animations/Stand/Self & others/NAO/Right_Slow_SAO_02",
"Right_Strong_SAO_01"   : "animations/Stand/Self & others/NAO/Right_Strong_SAO_01",
"Right_Strong_SAO_02"   : "animations/Stand/Self & others/NAO/Right_Strong_SAO_02",
"Right_Strong_SAO_03"   : "animations/Stand/Self & others/NAO/Right_Strong_SAO_03",
"Right_Strong_SAO_04"   : "animations/Stand/Self & others/NAO/Right_Strong_SAO_04",
"Right_Strong_SAO_05"   : "animations/Stand/Self & others/NAO/Right_Strong_SAO_05",
"Center_Neutral_SAT_01" : "animations/Stand/Space & time/NAO/Center_Neutral_SAT_01",
"Center_Neutral_SAT_02" : "animations/Stand/Space & time/NAO/Center_Neutral_SAT_02",
"Center_Neutral_SAT_03" : "animations/Stand/Space & time/NAO/Center_Neutral_SAT_03",
"Center_Neutral_SAT_04" : "animations/Stand/Space & time/NAO/Center_Neutral_SAT_04",
"Center_Slow_SAT_01"    : "animations/Stand/Space & time/NAO/Center_Slow_SAT_01",
"Center_Slow_SAT_02"    : "animations/Stand/Space & time/NAO/Center_Slow_SAT_02",
"Center_Slow_SAT_03"    : "animations/Stand/Space & time/NAO/Center_Slow_SAT_03",
"Center_Strong_SAT_01"  : "animations/Stand/Space & time/NAO/Center_Strong_SAT_01",
"Center_Strong_SAT_02"  : "animations/Stand/Space & time/NAO/Center_Strong_SAT_02",
"Left_Neutral_SAT_01"   : "animations/Stand/Space & time/NAO/Left_Neutral_SAT_01",
"Left_Neutral_SAT_02"   : "animations/Stand/Space & time/NAO/Left_Neutral_SAT_02",
"Left_Neutral_SAT_03"   : "animations/Stand/Space & time/NAO/Left_Neutral_SAT_03",
"Left_Neutral_SAT_04"   : "animations/Stand/Space & time/NAO/Left_Neutral_SAT_04",
"Left_Neutral_SAT_05"   : "animations/Stand/Space & time/NAO/Left_Neutral_SAT_05",
"Left_Neutral_SAT_06"   : "animations/Stand/Space & time/NAO/Left_Neutral_SAT_06",
"Left_Neutral_SAT_07"   : "animations/Stand/Space & time/NAO/Left_Neutral_SAT_07",
"Left_Neutral_SAT_08"   : "animations/Stand/Space & time/NAO/Left_Neutral_SAT_08",
"Left_Neutral_SAT_09"   : "animations/Stand/Space & time/NAO/Left_Neutral_SAT_09",
"Left_Neutral_SAT_10"   : "animations/Stand/Space & time/NAO/Left_Neutral_SAT_10",
"Left_Slow_SAT_01"      : "animations/Stand/Space & time/NAO/Left_Slow_SAT_01",
"Left_Strong_SAT_01"    : "animations/Stand/Space & time/NAO/Left_Strong_SAT_01",
"Left_Strong_SAT_02"    : "animations/Stand/Space & time/NAO/Left_Strong_SAT_02",
"Left_Strong_SAT_03"    : "animations/Stand/Space & time/NAO/Left_Strong_SAT_03",
"Left_Strong_SAT_04"    : "animations/Stand/Space & time/NAO/Left_Strong_SAT_04",
"Left_Strong_SAT_05"    : "animations/Stand/Space & time/NAO/Left_Strong_SAT_05",
"Left_Strong_SAT_06"    : "animations/Stand/Space & time/NAO/Left_Strong_SAT_06",
"Right_Neutral_SAT_01"  : "animations/Stand/Space & time/NAO/Right_Neutral_SAT_01",
"Right_Neutral_SAT_02"  : "animations/Stand/Space & time/NAO/Right_Neutral_SAT_02",
"Right_Neutral_SAT_03"  : "animations/Stand/Space & time/NAO/Right_Neutral_SAT_03",
"Right_Neutral_SAT_04"  : "animations/Stand/Space & time/NAO/Right_Neutral_SAT_04",
"Right_Neutral_SAT_05"  : "animations/Stand/Space & time/NAO/Right_Neutral_SAT_05",
"Right_Neutral_SAT_06"  : "animations/Stand/Space & time/NAO/Right_Neutral_SAT_06",
"Right_Neutral_SAT_07"  : "animations/Stand/Space & time/NAO/Right_Neutral_SAT_07",
"Right_Neutral_SAT_08"  : "animations/Stand/Space & time/NAO/Right_Neutral_SAT_08",
"Right_Neutral_SAT_09"  : "animations/Stand/Space & time/NAO/Right_Neutral_SAT_09",
"Right_Neutral_SAT_10"  : "animations/Stand/Space & time/NAO/Right_Neutral_SAT_10",
"Right_Slow_SAT_01"     : "animations/Stand/Space & time/NAO/Right_Slow_SAT_01",
"Right_Strong_SAT_01"   : "animations/Stand/Space & time/NAO/Right_Strong_SAT_01",
"Right_Strong_SAT_02"   : "animations/Stand/Space & time/NAO/Right_Strong_SAT_02",
"Right_Strong_SAT_03"   : "animations/Stand/Space & time/NAO/Right_Strong_SAT_03",
"Right_Strong_SAT_04"   : "animations/Stand/Space & time/NAO/Right_Strong_SAT_04",
"Right_Strong_SAT_05"   : "animations/Stand/Space & time/NAO/Right_Strong_SAT_05",
"Right_Strong_SAT_06"   : "animations/Stand/Space & time/NAO/Right_Strong_SAT_06",
# deprecated
"Bored_1"        : "animations/Stand/Emotions/Negative/Bored_1",
"Embarrassed_1"  : "animations/Stand/Emotions/Neutral/Embarrassed_1",
"Happy_4"        : "animations/Stand/Emotions/Positive/Happy_4",
"Hysterical_1"   : "animations/Stand/Emotions/Positive/Hysterical_1",
"Peaceful_1"     : "animations/Stand/Emotions/Positive/Peaceful_1",
"BowShort_1"     : "animations/Stand/Gestures/BowShort_1",
"But_1"          : "animations/Stand/Gestures/But_1",
"CalmDown_1"     : "animations/Stand/Gestures/CalmDown_1",
"CalmDown_5"     : "animations/Stand/Gestures/CalmDown_5",
"CalmDown_6"     : "animations/Stand/Gestures/CalmDown_6",
"Choice_1"       : "animations/Stand/Gestures/Choice_1",
"Desperate_1"    : "animations/Stand/Gestures/Desperate_1",
"Desperate_2"    : "animations/Stand/Gestures/Desperate_2",
"Desperate_4"    : "animations/Stand/Gestures/Desperate_4",
"Desperate_5"    : "animations/Stand/Gestures/Desperate_5",
"Enthusiastic_4" : "animations/Stand/Gestures/Enthusiastic_4",
"Enthusiastic_5" : "animations/Stand/Gestures/Enthusiastic_5",
"Everything_1"   : "animations/Stand/Gestures/Everything_1",
"Everything_2"   : "animations/Stand/Gestures/Everything_2",
"Everything_3"   : "animations/Stand/Gestures/Everything_3",
"Everything_4"   : "animations/Stand/Gestures/Everything_4",
"Excited_1"      : "animations/Stand/Gestures/Excited_1",
"Explain_1"      : "animations/Stand/Gestures/Explain_1",
"Explain_10"     : "animations/Stand/Gestures/Explain_10",
"Explain_11"     : "animations/Stand/Gestures/Explain_11",
"Explain_2"      : "animations/Stand/Gestures/Explain_2",
"Explain_3"      : "animations/Stand/Gestures/Explain_3",
"Explain_4"      : "animations/Stand/Gestures/Explain_4",
"Explain_5"      : "animations/Stand/Gestures/Explain_5",
"Explain_6"      : "animations/Stand/Gestures/Explain_6",
"Explain_7"      : "animations/Stand/Gestures/Explain_7",
"Explain_8"      : "animations/Stand/Gestures/Explain_8",
"Far_1"          : "animations/Stand/Gestures/Far_1",
"Far_2"          : "animations/Stand/Gestures/Far_2",
"Far_3"          : "animations/Stand/Gestures/Far_3",
"Give_3"         : "animations/Stand/Gestures/Give_3",
"Give_4"         : "animations/Stand/Gestures/Give_4",
"Give_5"         : "animations/Stand/Gestures/Give_5",
"Give_6"         : "animations/Stand/Gestures/Give_6",
"Hey_1"          : "animations/Stand/Gestures/Hey_1",
"Hey_3"          : "animations/Stand/Gestures/Hey_3",
"Hey_4"          : "animations/Stand/Gestures/Hey_4",
"Hey_6"          : "animations/Stand/Gestures/Hey_6",
"IDontKnow_1"    : "animations/Stand/Gestures/IDontKnow_1",
"IDontKnow_2"    : "animations/Stand/Gestures/IDontKnow_2",
"IDontKnow_3"    : "animations/Stand/Gestures/IDontKnow_3",
"Me_1"           : "animations/Stand/Gestures/Me_1",
"Me_2"           : "animations/Stand/Gestures/Me_2",
"Me_4"           : "animations/Stand/Gestures/Me_4",
"Me_7"           : "animations/Stand/Gestures/Me_7",
"No_1"           : "animations/Stand/Gestures/No_1",
"No_2"           : "animations/Stand/Gestures/No_2",
"No_3"           : "animations/Stand/Gestures/No_3",
"No_8"           : "animations/Stand/Gestures/No_8",
"No_9"           : "animations/Stand/Gestures/No_9",
"Nothing_2"      : "animations/Stand/Gestures/Nothing_2",
"Please_1"       : "animations/Stand/Gestures/Please_1",
"ShowFloor_1"    : "animations/Stand/Gestures/ShowFloor_1",
"ShowFloor_3"    : "animations/Stand/Gestures/ShowFloor_3",
"ShowFloor_4"    : "animations/Stand/Gestures/ShowFloor_4",
"ShowSky_1"      : "animations/Stand/Gestures/ShowSky_1",
"ShowSky_2"      : "animations/Stand/Gestures/ShowSky_2",
"ShowSky_3"      : "animations/Stand/Gestures/ShowSky_3",  # added, not listed on the website
"ShowSky_4"      : "animations/Stand/Gestures/ShowSky_4",
"ShowSky_5"      : "animations/Stand/Gestures/ShowSky_5",
"ShowSky_6"      : "animations/Stand/Gestures/ShowSky_6",
"ShowSky_7"      : "animations/Stand/Gestures/ShowSky_7",
"ShowSky_8"      : "animations/Stand/Gestures/ShowSky_8",
"ShowSky_9"      : "animations/Stand/Gestures/ShowSky_9",
"ShowSky_10"     : "animations/Stand/Gestures/ShowSky_10", # added, not listed on the website
"ShowSky_11"     : "animations/Stand/Gestures/ShowSky_11",
"ShowSky_12"     : "animations/Stand/Gestures/ShowSky_12", # added, not listed on the website
"ShowTablet_2"   : "animations/Stand/Gestures/ShowTablet_2",
"ShowTablet_3"   : "animations/Stand/Gestures/ShowTablet_3",
"Thinking_1"     : "animations/Stand/Gestures/Thinking_1",
"Thinking_3"     : "animations/Stand/Gestures/Thinking_3",
"Thinking_4"     : "animations/Stand/Gestures/Thinking_4",
"Thinking_6"     : "animations/Stand/Gestures/Thinking_6",
"Thinking_8"     : "animations/Stand/Gestures/Thinking_8",
"Yes_1"          : "animations/Stand/Gestures/Yes_1",
"Yes_2"          : "animations/Stand/Gestures/Yes_2",
"Yes_3"          : "animations/Stand/Gestures/Yes_3",
"YouKnowWhat_1"  : "animations/Stand/Gestures/YouKnowWhat_1",
"YouKnowWhat_2"  : "animations/Stand/Gestures/YouKnowWhat_2",
"YouKnowWhat_3"  : "animations/Stand/Gestures/YouKnowWhat_3",
"YouKnowWhat_5"  : "animations/Stand/Gestures/YouKnowWhat_5",
"YouKnowWhat_6"  : "animations/Stand/Gestures/YouKnowWhat_6",
"You_1"          : "animations/Stand/Gestures/You_1",
"You_4"          : "animations/Stand/Gestures/You_4",
"ShowSky_1"      : "animations/Stand/Waiting/ShowSky_1",
"ShowSky_2"      : "animations/Stand/Waiting/ShowSky_2",
"Think_1"        : "animations/Stand/Waiting/Think_1",
"Think_2"        : "animations/Stand/Waiting/Think_2",
"Think_3"        : "animations/Stand/Waiting/Think_3",
"Joy_1"          : "animations/Stand/Gestures/Joy_1"         # added, not listed on the website
# deprecated and not available
#"Hesitation_1"  : "animations/Stand/Gestures/Hesitation_1",
#"BodyTalk_1"  : "animations/Stand/BodyTalk/BodyTalk_1",
#"BodyTalk_2"  : "animations/Stand/BodyTalk/BodyTalk_2",
#"BodyTalk_3"  : "animations/Stand/BodyTalk/BodyTalk_3",
#"BodyTalk_4"  : "animations/Stand/BodyTalk/BodyTalk_4",
#"BodyTalk_5"  : "animations/Stand/BodyTalk/BodyTalk_5",
#"BodyTalk_6"  : "animations/Stand/BodyTalk/BodyTalk_6",
#"BodyTalk_7"  : "animations/Stand/BodyTalk/BodyTalk_7",
#"BodyTalk_8"  : "animations/Stand/BodyTalk/BodyTalk_8",
#"BodyTalk_9"  : "animations/Stand/BodyTalk/BodyTalk_9",
#"BodyTalk_10" : "animations/Stand/BodyTalk/BodyTalk_10",
#"BodyTalk_11" : "animations/Stand/BodyTalk/BodyTalk_11",
#"BodyTalk_12" : "animations/Stand/BodyTalk/BodyTalk_12",
#"BodyTalk_13" : "animations/Stand/BodyTalk/BodyTalk_13",
#"BodyTalk_14" : "animations/Stand/BodyTalk/BodyTalk_14",
#"BodyTalk_15" : "animations/Stand/BodyTalk/BodyTalk_15",
#"BodyTalk_16" : "animations/Stand/BodyTalk/BodyTalk_16",
#"BodyTalk_17" : "animations/Stand/BodyTalk/BodyTalk_17",
#"BodyTalk_18" : "animations/Stand/BodyTalk/BodyTalk_18",
#"BodyTalk_19" : "animations/Stand/BodyTalk/BodyTalk_19",
#"BodyTalk_20" : "animations/Stand/BodyTalk/BodyTalk_20",
#"BodyTalk_21" : "animations/Stand/BodyTalk/BodyTalk_21",
#"BodyTalk_22" : "animations/Stand/BodyTalk/BodyTalk_22"
}

Pepper_animation_tags = {
"affirmative_context"  : ["Center_Strong_AFF_06" , "Center_Strong_AFF_04" , "Left_Neutral_AFF_06" , "Center_Strong_AFF_08" , "Center_Strong_AFF_07" , "Right_Neutral_AFF_06" , "Center_Neutral_AFF_11" , "Right_Slow_AFF_02" , "Left_Slow_AFF_03" , "Center_Strong_AFF_05" , "Center_Neutral_AFF_02" , "Center_Slow_AFF_02" , "Center_Neutral_AFF_10" , "Left_Slow_AFF_02" , "Center_Neutral_AFF_01" , "Right_Neutral_AFF_04" , "Left_Neutral_AFF_04" , "Center_Strong_AFF_01" , "Right_Slow_AFF_03" , "Center_Neutral_AFF_12" , "Center_Slow_AFF_03"],
"anterior"             : ["Left_Slow_SAT_01" , "Left_Neutral_SAT_08" , "Right_Neutral_SAT_08" , "Right_Neutral_SAT_04" , "Left_Neutral_SAT_10" , "Left_Neutral_SAT_04" , "Left_Neutral_SAT_07" , "Right_Slow_SAT_01" , "Center_Neutral_SAT_02" , "Right_Neutral_SAT_07" , "Right_Neutral_SAT_10"],
"comparison"           : ["Left_Neutral_ENU_05" , "Center_Slow_ENU_02" , "Right_Strong_ENU_04" , "Center_Neutral_ENU_02" , "Right_Strong_ENU_02" , "Center_Slow_ENU_01" , "Center_Slow_ENU_03" , "Left_Strong_ENU_02" , "Right_Neutral_ENU_05" , "Left_Strong_ENU_04"],
"confirmation"         : ["Center_Neutral_AFF_08" , "Center_Neutral_AFF_09" , "Center_Neutral_AFF_07" , "Center_Strong_AFF_06" , "Right_Neutral_AFF_02" , "Center_Neutral_AFF_06" , "Left_Neutral_AFF_05" , "Center_Slow_AFF_01" , "Center_Slow_AFF_05" , "Left_Neutral_AFF_02" , "Center_Neutral_AFF_13" , "Left_Strong_AFF_02" , "Right_Strong_AFF_02" , "Right_Neutral_AFF_05" , "Center_Strong_AFF_02" , "Right_Slow_AFF_01" , "Center_Neutral_AFF_04" , "Left_Slow_AFF_01" , "Center_Slow_AFF_06" , "Center_Neutral_AFF_05"],
"disappointment"       : ["Center_Strong_EXC_05" , "Center_Neutral_EXC_04" , "Center_Strong_EXC_06" , "Center_Strong_EXC_03" , "Right_Strong_EXC_02" , "Left_Strong_EXC_02" , "Center_Slow_EXC_02"],
"diversity"            : ["Center_Neutral_ENU_06" , "Left_Neutral_ENU_05" , "Left_Neutral_ENU_02" , "Center_Slow_ENU_02" , "Center_Slow_ENU_04" , "Right_Neutral_ENU_03" , "Left_Neutral_ENU_03" , "Right_Neutral_ENU_02" , "Right_Neutral_ENU_01" , "Left_Neutral_ENU_01" , "Center_Neutral_ENU_01" , "Center_Slow_ENU_01" , "Center_Slow_ENU_03" , "Left_Strong_ENU_03" , "Right_Strong_ENU_03" , "Right_Neutral_ENU_05"],
"exclamation"          : ["Left_Neutral_EXC_02" , "Right_Strong_EXC_01" , "Center_Strong_EXC_05" , "Center_Strong_EXC_09" , "Center_Strong_EXC_08" , "Right_Neutral_EXC_02" , "Left_Strong_EXC_04" , "Left_Strong_EXC_01" , "Center_Strong_EXC_06" , "Center_Strong_EXC_03" , "Center_Neutral_EXC_03" , "Center_Neutral_EXC_05" , "Center_Strong_EXC_10" , "Center_Slow_EXC_02" , "Center_Neutral_EXC_02" , "Center_Slow_EXC_03" , "Center_Strong_EXC_04" , "Right_Strong_EXC_04"],
"global"               : ["Left_Neutral_SAT_06" , "Center_Slow_SAT_02" , "Center_Neutral_SAT_01" , "Center_Slow_SAT_03" , "Center_Strong_SAT_02" , "Center_Neutral_SAT_03" , "Right_Neutral_SAT_06"],
"group"                : ["Right_Strong_SAO_05" , "Left_Neutral_SAO_06" , "Left_Neutral_SAO_05" , "Left_Strong_SAO_05" , "Center_Neutral_SAO_01" , "Right_Neutral_SAO_06" , "Center_Neutral_SAO_02" , "Center_Neutral_SAO_04" , "Right_Neutral_SAO_05"],
"hesitation"           : ["Center_Neutral_QUE_09" , "Right_Neutral_QUE_02" , "Left_Neutral_QUE_01" , "Right_Neutral_QUE_01" , "Center_Neutral_QUE_06" , "Center_Slow_QUE_01" , "Center_Slow_QUE_02" , "Center_Strong_QUE_01" , "Center_Neutral_QUE_10" , "Left_Neutral_QUE_02" , "Center_Neutral_QUE_02" , "Center_Neutral_QUE_05" , "Center_Strong_QUE_02" , "Center_Neutral_QUE_01" , "Center_Slow_QUE_03"], # "Hesitation_1" not available => removed 
"interrogative"        : ["Center_Neutral_QUE_09" , "Center_Strong_QUE_03" , "Left_Neutral_QUE_01" , "Right_Neutral_QUE_03" , "Right_Neutral_QUE_01" , "Center_Neutral_QUE_04" , "Center_Slow_QUE_02" , "Center_Neutral_QUE_03" , "Center_Neutral_QUE_02" , "Center_Neutral_QUE_08" , "Left_Neutral_QUE_03" , "Center_Slow_QUE_03"],
"joy"                  : ["Joy_1" , "Right_Strong_EXC_01" , "Center_Strong_EXC_09" , "Right_Neutral_EXC_05" , "Left_Strong_EXC_03" , "Left_Strong_EXC_01" , "Left_Neutral_EXC_05" , "Center_Slow_EXC_01" , "Center_Strong_EXC_03" , "Right_Strong_EXC_03" , "Center_Neutral_EXC_03" , "Center_Neutral_EXC_08" , "Center_Neutral_EXC_07" , "Center_Neutral_EXC_06" , "Center_Strong_EXC_04" , "Center_Neutral_EXC_01"],
"left_side"            : ["Left_Neutral_SAT_06" , "Left_Strong_SAT_02" , "Left_Neutral_SAT_03" , "Left_Slow_SAT_01" , "Left_Neutral_SAT_08" , "Left_Strong_SAT_03" , "Left_Strong_SAT_05" , "Left_Strong_SAT_06" , "Left_Neutral_SAT_01" , "Left_Neutral_SAT_10" , "Left_Neutral_SAT_04" , "Left_Strong_SAT_01" , "Left_Strong_SAT_04" , "Left_Neutral_SAT_07" , "Left_Neutral_SAT_09" , "Left_Neutral_SAT_05" , "Left_Neutral_SAT_02"],
"longrange"            : ["Left_Strong_SAT_02" , "Left_Neutral_SAT_03" , "Center_Slow_SAT_02" , "Right_Strong_SAT_02" , "Right_Strong_SAT_04" , "Left_Strong_SAT_01" , "Right_Neutral_SAT_03" , "Left_Strong_SAT_04" , "Right_Strong_SAT_01"],
"negative_context"     : ["Left_Strong_NEG_01" , "Left_Strong_NEG_03" , "Center_Slow_NEG_01" , "Right_Neutral_NEG_01" , "Right_Strong_NEG_04" , "Center_Strong_NEG_03" , "Right_Strong_NEG_02" , "Left_Strong_NEG_04" , "Left_Strong_NEG_02" , "Right_Strong_NEG_03" , "Center_Neutral_NEG_04" , "Center_Strong_NEG_04" , "Center_Strong_NEG_05" , "Right_Strong_NEG_01" , "Left_Neutral_NEG_01"],
"overall"              : ["Center_Neutral_ENU_06" , "Left_Neutral_ENU_02" , "Right_Strong_ENU_04" , "Center_Neutral_ENU_02" , "Right_Neutral_ENU_02" , "Right_Neutral_ENU_01" , "Right_Neutral_ENU_04" , "Left_Neutral_ENU_04" , "Center_Strong_ENU_02" , "Right_Strong_ENU_02" , "Left_Neutral_ENU_01" , "Center_Strong_ENU_01" , "Center_Neutral_ENU_04" , "Center_Strong_ENU_03" , "Center_Neutral_ENU_07" , "Left_Strong_ENU_03" , "Right_Strong_ENU_03" , "Center_Neutral_ENU_03" , "Left_Strong_ENU_02" , "Left_Strong_ENU_04"],
"people"               : ["Left_Neutral_SAO_03" , "Left_Neutral_SAO_01" , "Right_Neutral_SAO_04" , "Left_Slow_SAO_01" , "Right_Neutral_SAO_03" , "Right_Neutral_SAO_02" , "Left_Neutral_SAO_02" , "Right_Slow_SAO_01" , "Left_Neutral_SAO_04" , "Center_Neutral_SAO_01" , "Left_Strong_SAO_01" , "Center_Neutral_SAO_03" , "Right_Strong_SAO_01" , "Right_Neutral_SAO_01"],
"refusal"              : ["Center_Neutral_NEG_01" , "Left_Strong_NEG_01" , "Center_Slow_NEG_01" , "Right_Neutral_NEG_01" , "Center_Neutral_NEG_02" , "Center_Strong_NEG_01" , "Center_Neutral_NEG_04" , "Center_Neutral_NEG_03" , "Right_Strong_NEG_01" , "Center_Slow_NEG_02" , "Left_Neutral_NEG_01"],
"right_side"           : ["Right_Neutral_SAT_05" , "Right_Strong_SAT_02" , "Right_Strong_SAT_06" , "Center_Neutral_SAT_04" , "Right_Strong_SAT_04" , "Right_Neutral_SAT_08" , "Right_Neutral_SAT_04" , "Right_Neutral_SAT_03" , "Right_Neutral_SAT_02" , "Right_Slow_SAT_01" , "Right_Neutral_SAT_01" , "Right_Neutral_SAT_09" , "Right_Neutral_SAT_07" , "Right_Strong_SAT_03" , "Right_Strong_SAT_05" , "Right_Neutral_SAT_10" , "Right_Neutral_SAT_06" , "Right_Strong_SAT_01"],
"self"                 : ["Left_Slow_SAO_02" , "Right_Slow_SAO_02" , "Right_Strong_SAO_03" , "Left_Neutral_SAO_05" , "Left_Strong_SAO_03" , "Center_Neutral_SAO_02" , "Right_Neutral_SAO_05"],
"shortrange"           : ["Right_Neutral_SAT_05" , "Left_Strong_SAT_03" , "Center_Neutral_SAT_04" , "Center_Strong_SAT_02" , "Left_Neutral_SAT_01" , "Center_Strong_SAT_01" , "Center_Slow_SAT_01" , "Left_Neutral_SAT_09" , "Left_Neutral_SAT_05" , "Right_Neutral_SAT_02" , "Right_Neutral_SAT_01" , "Right_Neutral_SAT_09" , "Right_Strong_SAT_03" , "Left_Neutral_SAT_02"],
"top"                  : ["ShowSky_1" , "ShowSky_10" , "ShowSky_11" , "ShowSky_12" , "ShowSky_2" , "ShowSky_3" , "ShowSky_4" , "ShowSky_5" , "ShowSky_6" , "ShowSky_7" , "ShowSky_8" , "ShowSky_9" , "Left_Neutral_SAT_03" , "Left_Slow_SAT_01" , "Right_Strong_SAT_06" , "Left_Strong_SAT_05" , "Left_Strong_SAT_06" , "Right_Neutral_SAT_03" , "Right_Slow_SAT_01" , "Center_Neutral_SAT_02" , "Right_Strong_SAT_05"],
"user"                 : ["Right_Strong_SAO_05" , "Left_Neutral_SAO_03" , "Left_Neutral_SAO_06" , "Right_Strong_SAO_02" , "Left_Slow_SAO_01" , "Center_Strong_SAO_02" , "Right_Neutral_SAO_03" , "Right_Strong_SAO_04" , "Center_Neutral_SAO_05" , "Center_Strong_SAO_01" , "Right_Slow_SAO_01" , "Left_Strong_SAO_05" , "Left_Strong_SAO_04" , "Left_Strong_SAO_02" , "Right_Neutral_SAO_06" , "Left_Strong_SAO_01" , "Center_Neutral_SAO_04" , "Center_Neutral_SAO_03" , "Right_Strong_SAO_01"]
}
